name: GPT Processing

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  process-with-gpt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install my-gpt package
        run: |
          python -m pip install --upgrade pip
          pip install path/to/my_gpt_package.whl

      - name: Process text and create files
        run: |
          # Replace with the command you use to run your package and process text
          my-gpt-command input.txt

      - name: Create a new branch
        run: |
          ORIGINAL_BRANCH_NAME=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          NEW_BRANCH_NAME="${ORIGINAL_BRANCH_NAME}-gptOutput"
          git checkout -b $NEW_BRANCH_NAME

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add GPT processed files"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.NEW_BRANCH_NAME }}
