name: GPT Processing v8

on:
  workflow_dispatch:
    inputs:
      file_name:
        description: 'file_name (asdf.py)'
        required: true
        type: string
      class_or_method:
        description: 'class_or_method (InventoryManager)'
        required: true
        type: string
      branch:
        description: 'Select the branch to run the workflow on'
        required: true
        type: choice
        options:
          - dev
          - main
      target_branch:
        description: 'Select the target branch for the pull request'
        required: true
        type: choice
        options:
          - dev
          - main

jobs:
  process-with-gpt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install my-gpt package
        run: |
          python -m pip install --upgrade pip
          pip install --force-reinstall whl/adchackathon202405t1-0.0.7-py3-none-any.whl

      - name: Process with my-gpt package
        run: |
          python -m src --file_name "${{ github.event.inputs.file_name }}" --class_or_method "${{ github.event.inputs.class_or_method }}"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Create and push new branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b ${{ github.event.inputs.branch }}-${{ github.run_id }}
          git add -A
          git commit -m "Processed output by GitHub Action" || echo "No changes to commit"
          git push --set-upstream origin ${{ github.event.inputs.branch }}-${{ github.run_id }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Processed output by GitHub Action"
          branch: ${{ github.event.inputs.branch }}-${{ github.run_id }}
          base: ${{ github.event.inputs.target_branch }}
          title: "Processed output by GitHub Action"
          body: "This PR contains processed output by GitHub Action."
